version: "2"
services: 
  zentao:
    image: dodoinblue/zentao-int:pro
    container_name: zentao
    ports:
      - "80:80"
      - "3306:3306"
    # if web response code: 310 ERR_TOO_MANY_REDIRECTS, please use host mode.
#    network_mode: "host"
    environment:
    # specifies you own account and password.
      USER: "root"
      PASSWD: "123456"
      BIND_ADDRESS: "false"
      SMTP_HOST: "163.177.90.125 smtp.exmail.qq.com"
    volumes:
    # specifies the path replace "./data".
      - ./data:/opt/zbox/
    restart: always
